const { PrismaClient } = require("@prisma/client")

const prisma = new PrismaClient()

async function main() {
  // Usuario base para asociar facturas (tu usuario actual)
  const seedEmail = "joelcordero728@gmail.com"
  const seedUsername = "joel"

  const user = await prisma.user.upsert({
    where: { email: seedEmail },
    update: {},
    create: {
      email: seedEmail,
      username: seedUsername,
      // contraseña dummy (no se usa en login real porque ya tenés tu usuario creado)
      password: "seed-password",
    },
  })

  // Ingresos de ejemplo
  await prisma.income.createMany({
    data: [
      {
        ven_tipimp: "I",
        ven_gra05: 0,
        ven_iva05: 0,
        ven_disg05: 0,
        cta_iva05: "4.1.1.02",
        ven_rubgra: 1500000,
        ven_rubg05: 0,
        ven_disexe: 0,
        ven_numero: "001-001-0000001",
        ven_imputa: "VENTAS",
        ven_sucurs: "1",
        generar: 0,
        form_pag: "Contado",
        ven_centro: "CENTRAL",
        ven_clie: "80000001-0",
        ven_cuenta: "1.1.3.01",
        ven_clinom: "Cliente Ejemplo S.A.",
        ven_tipofa: "Factura",
        ven_fecha: "2026-02-01",
        ven_totfac: 1500000,
        ven_exenta: 0,
        ven_gravad: 1500000,
        ven_iva: 150000,
        ven_aux: "WEB",
        ven_retenc: 0,
        ven_ctrl: "A",
        ven_con: "VENTA CONTADO",
        ven_cuota: "1/1",
        ven_fecven: "2026-02-01",
        cant_dias: 0,
        origen: "MANUAL",
        cambio: 1,
        valor: 1500000,
        moneda: "PYG",
        exen_dolar: 0,
        concepto: "VENTAS",
        cta_iva: "4.1.1.01",
        cta_caja: "1.1.1.01",
        tkdesde: "0001",
        tkhasta: "0001",
        caja: "CAJA PRINCIPAL",
        ven_disgra: 0,
        forma_devo: "NINGUNA",
        ven_cuense: null,
        anular: false,
        reproceso: false,
        cuenta_exe: null,
        usu_ide: "admin",
        rucvennrotim: "12345678-9",
        ventirptip: "G",
        clieasi: "80000001-0",
        ventirpgra: 0,
        ventirpexe: 0,
        irpc: 0,
        ivasimplificado: 0,
        nroFacAso: null,
        TimFacAso: 0,
        userId: user.id,
      },
      {
        ven_tipimp: "I",
        ven_gra05: 500000,
        ven_iva05: 25000,
        ven_disg05: 0,
        cta_iva05: "4.1.1.02",
        ven_rubgra: 0,
        ven_rubg05: 500000,
        ven_disexe: 0,
        ven_numero: "001-001-0000002",
        ven_imputa: "VENTAS",
        ven_sucurs: "2",
        generar: 0,
        form_pag: "Crédito",
        ven_centro: "SUCURSAL",
        ven_clie: "80000002-8",
        ven_cuenta: "1.1.3.02",
        ven_clinom: "Juan Pérez",
        ven_tipofa: "Factura",
        ven_fecha: "2026-02-10",
        ven_totfac: 500000,
        ven_exenta: 0,
        ven_gravad: 500000,
        ven_iva: 50000,
        ven_aux: "POS",
        ven_retenc: 0,
        ven_ctrl: "B",
        ven_con: "VENTA CRÉDITO",
        ven_cuota: "1/3",
        ven_fecven: "2026-03-10",
        cant_dias: 30,
        origen: "MANUAL",
        cambio: 1,
        valor: 500000,
        moneda: "PYG",
        exen_dolar: 0,
        concepto: "VENTAS",
        cta_iva: "4.1.1.01",
        cta_caja: "1.1.1.02",
        tkdesde: "0002",
        tkhasta: "0002",
        caja: "CAJA SUCURSAL",
        ven_disgra: 0,
        forma_devo: "NINGUNA",
        ven_cuense: null,
        anular: false,
        reproceso: false,
        cuenta_exe: null,
        usu_ide: "admin",
        rucvennrotim: "12345678-9",
        ventirptip: "G",
        clieasi: "80000002-8",
        ventirpgra: 0,
        ventirpexe: 0,
        irpc: 0,
        ivasimplificado: 0,
        nroFacAso: null,
        TimFacAso: 0,
        userId: user.id,
      },
    ],
  })

  // Egresos de ejemplo
  await prisma.egress.createMany({
    data: [
      {
        com_numero: "001-001-0000100",
        generar: 0,
        cta_iva: "4.1.1.01",
        cta_caja: "1.1.1.01",
        form_pag: "Crédito",
        com_imputa: "COMPRAS",
        com_sucurs: "1",
        com_centro: "CENTRAL",
        com_provee: "90000001-3",
        com_cuenta: "2.1.1.01",
        com_prvnom: "Proveedor Demo S.R.L.",
        com_tipofa: "Factura",
        com_fecha: "2026-02-05",
        com_totfac: 2500000,
        com_exenta: 0,
        com_gravad: 2500000,
        com_iva: 250000,
        com_import: 2500000,
        com_aux: "SISTEMA",
        com_con: "COMPRA MERCADERÍAS",
        com_cuota: "1/2",
        com_fecven: "2026-03-05",
        com_ordenp: "OP-0001",
        cant_dias: 30,
        com_x: "",
        moneda: "PYG",
        cambio: 1,
        valor: 2500000,
        origen: "MANUAL",
        exen_dolar: 0,
        com_disexe: 0,
        com_disgra: 0,
        forma_devo: "NINGUNA",
        retencion: 0,
        porcentaje: 0,
        reproceso: false,
        cuenta_exe: null,
        com_tipimp: "L",
        com_gra05: 0,
        com_iva05: 0,
        com_disg05: 0,
        cta_iva05: "4.1.1.02",
        com_rubgra: 2500000,
        com_rubgra05: 0,
        com_ctag05: null,
        com_rubexe: 0,
        com_saldo: 0,
        com_timbra: "98765432-1",
        RetNroFac: null,
        RetRetFec: null,
        RetTim: null,
        RetIva: 0,
        RetRen: 0,
        RetIvaCon: null,
        RetRetCon: null,
        TipoExport: null,
        Retiva05: 0,
        IrpTip: null,
        IrpInc: null,
        IrpMon: null,
        IrpTip2: null,
        IrpInc2: null,
        IrpMon2: null,
        irpc: 0,
        ivasimplificado: 0,
        comnroncaso: null,
        comtimnncaso: null,
        comctaban: null,
        combanraz: null,
        comvirtual: false,
        com_timven: null,
        userId: user.id,
      },
      {
        com_numero: "001-001-0000101",
        generar: 0,
        cta_iva: "4.1.1.01",
        cta_caja: "1.1.1.01",
        form_pag: "Contado",
        com_imputa: "COMPRAS",
        com_sucurs: "2",
        com_centro: "SUCURSAL",
        com_provee: "90000002-1",
        com_cuenta: "2.1.1.02",
        com_prvnom: "Servicios Profesionales S.A.",
        com_tipofa: "Factura",
        com_fecha: "2026-02-12",
        com_totfac: 800000,
        com_exenta: 0,
        com_gravad: 800000,
        com_iva: 80000,
        com_import: 800000,
        com_aux: "SISTEMA",
        com_con: "PAGO SERVICIOS",
        com_cuota: "1/1",
        com_fecven: "2026-02-12",
        com_ordenp: "OP-0002",
        cant_dias: 0,
        com_x: "",
        moneda: "PYG",
        cambio: 1,
        valor: 800000,
        origen: "MANUAL",
        exen_dolar: 0,
        com_disexe: 0,
        com_disgra: 0,
        forma_devo: "NINGUNA",
        retencion: 0,
        porcentaje: 0,
        reproceso: false,
        cuenta_exe: null,
        com_tipimp: "L",
        com_gra05: 0,
        com_iva05: 0,
        com_disg05: 0,
        cta_iva05: "4.1.1.02",
        com_rubgra: 800000,
        com_rubgra05: 0,
        com_ctag05: null,
        com_rubexe: 0,
        com_saldo: 0,
        com_timbra: "98765432-1",
        RetNroFac: null,
        RetRetFec: null,
        RetTim: null,
        RetIva: 0,
        RetRen: 0,
        RetIvaCon: null,
        RetRetCon: null,
        TipoExport: null,
        Retiva05: 0,
        IrpTip: null,
        IrpInc: null,
        IrpMon: null,
        IrpTip2: null,
        IrpInc2: null,
        IrpMon2: null,
        irpc: 0,
        ivasimplificado: 0,
        comnroncaso: null,
        comtimnncaso: null,
        comctaban: null,
        combanraz: null,
        comvirtual: false,
        com_timven: null,
        userId: user.id,
      },
    ],
  })

  // Logs de proceso de facturas de ejemplo
  await prisma.invoiceProcessLog.createMany({
    data: [
      {
        fileName: "carga_manual_ingresos.csv",
        invoiceType: "income",
        receiptNumber: "001-001-0000001",
        status: "SUCCESS",
        errorMessage: null,
      },
      {
        fileName: "carga_manual_ingresos.csv",
        invoiceType: "income",
        receiptNumber: "001-001-0000002",
        status: "SUCCESS",
        errorMessage: null,
      },
      {
        fileName: "carga_manual_egresos.csv",
        invoiceType: "egress",
        receiptNumber: "001-001-0000100",
        status: "SUCCESS",
        errorMessage: null,
      },
      {
        fileName: "carga_manual_egresos.csv",
        invoiceType: "egress",
        receiptNumber: "001-001-0000101",
        status: "SUCCESS",
        errorMessage: null,
      },
    ],
  })
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })

