/*
  Warnings:

  - You are about to drop the column `condition` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `cotization` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `currency` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `dueDate` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `isVirtual` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `nonDeductibleExpense` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `notRetain` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `receiptNumber` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `ruc` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `stamped` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `subsidiary` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `totalAmount` on the `Egress` table. All the data in the column will be lost.
  - You are about to drop the column `condition` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `cotization` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `currency` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `receiptNumber` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `ruc` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `stamped` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `subsidiary` on the `Income` table. All the data in the column will be lost.
  - You are about to drop the column `totalAmount` on the `Income` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Egress" DROP COLUMN "condition",
DROP COLUMN "cotization",
DROP COLUMN "currency",
DROP COLUMN "dueDate",
DROP COLUMN "isVirtual",
DROP COLUMN "nonDeductibleExpense",
DROP COLUMN "notRetain",
DROP COLUMN "receiptNumber",
DROP COLUMN "ruc",
DROP COLUMN "stamped",
DROP COLUMN "subsidiary",
DROP COLUMN "totalAmount",
ADD COLUMN     "IrpInc" TEXT,
ADD COLUMN     "IrpInc2" TEXT,
ADD COLUMN     "IrpMon" TEXT,
ADD COLUMN     "IrpMon2" TEXT,
ADD COLUMN     "IrpTip" TEXT,
ADD COLUMN     "IrpTip2" TEXT,
ADD COLUMN     "RetIva" DECIMAL(18,2),
ADD COLUMN     "RetIvaCon" TEXT,
ADD COLUMN     "RetNroFac" TEXT,
ADD COLUMN     "RetRen" DECIMAL(18,2),
ADD COLUMN     "RetRetCon" TEXT,
ADD COLUMN     "RetRetFec" TEXT,
ADD COLUMN     "RetTim" TEXT,
ADD COLUMN     "Retiva05" DECIMAL(18,2),
ADD COLUMN     "TipoExport" TEXT,
ADD COLUMN     "cambio" DECIMAL(18,4),
ADD COLUMN     "cant_dias" INTEGER DEFAULT 0,
ADD COLUMN     "com_aux" TEXT,
ADD COLUMN     "com_centro" TEXT,
ADD COLUMN     "com_con" TEXT,
ADD COLUMN     "com_ctag05" TEXT,
ADD COLUMN     "com_cuenta" TEXT,
ADD COLUMN     "com_cuota" TEXT,
ADD COLUMN     "com_disexe" DECIMAL(18,2),
ADD COLUMN     "com_disg05" DECIMAL(18,2),
ADD COLUMN     "com_disgra" DECIMAL(18,2),
ADD COLUMN     "com_exenta" DECIMAL(18,2),
ADD COLUMN     "com_fecha" TEXT,
ADD COLUMN     "com_fecven" TEXT DEFAULT '1753-01-01',
ADD COLUMN     "com_gra05" DECIMAL(18,2),
ADD COLUMN     "com_gravad" DECIMAL(18,2),
ADD COLUMN     "com_import" DECIMAL(18,2),
ADD COLUMN     "com_imputa" TEXT,
ADD COLUMN     "com_iva" DECIMAL(18,2),
ADD COLUMN     "com_iva05" DECIMAL(18,2),
ADD COLUMN     "com_numero" TEXT,
ADD COLUMN     "com_ordenp" TEXT,
ADD COLUMN     "com_provee" TEXT,
ADD COLUMN     "com_prvnom" TEXT,
ADD COLUMN     "com_rubexe" DECIMAL(18,2),
ADD COLUMN     "com_rubgra" DECIMAL(18,2),
ADD COLUMN     "com_rubgra05" DECIMAL(18,2),
ADD COLUMN     "com_saldo" DECIMAL(18,2),
ADD COLUMN     "com_sucurs" TEXT,
ADD COLUMN     "com_timbra" TEXT,
ADD COLUMN     "com_timven" TEXT,
ADD COLUMN     "com_tipimp" TEXT DEFAULT 'L',
ADD COLUMN     "com_tipofa" TEXT,
ADD COLUMN     "com_totfac" DECIMAL(18,2),
ADD COLUMN     "com_x" TEXT,
ADD COLUMN     "combanraz" TEXT,
ADD COLUMN     "comctaban" TEXT,
ADD COLUMN     "comnroncaso" TEXT,
ADD COLUMN     "comtimnncaso" TEXT,
ADD COLUMN     "comvirtual" BOOLEAN,
ADD COLUMN     "cta_caja" TEXT,
ADD COLUMN     "cta_iva" TEXT,
ADD COLUMN     "cta_iva05" TEXT,
ADD COLUMN     "cuenta_exe" TEXT,
ADD COLUMN     "exen_dolar" DECIMAL(18,2),
ADD COLUMN     "form_pag" TEXT,
ADD COLUMN     "forma_devo" TEXT,
ADD COLUMN     "generar" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "irpc" DECIMAL(18,2),
ADD COLUMN     "ivasimplificado" DECIMAL(18,2),
ADD COLUMN     "moneda" TEXT,
ADD COLUMN     "origen" TEXT,
ADD COLUMN     "porcentaje" DECIMAL(18,2),
ADD COLUMN     "reproceso" BOOLEAN DEFAULT false,
ADD COLUMN     "retencion" DECIMAL(18,2),
ADD COLUMN     "valor" DECIMAL(18,2);

-- AlterTable
ALTER TABLE "Income" DROP COLUMN "condition",
DROP COLUMN "cotization",
DROP COLUMN "currency",
DROP COLUMN "receiptNumber",
DROP COLUMN "ruc",
DROP COLUMN "stamped",
DROP COLUMN "subsidiary",
DROP COLUMN "totalAmount",
ADD COLUMN     "TimFacAso" INTEGER DEFAULT 0,
ADD COLUMN     "anular" BOOLEAN DEFAULT false,
ADD COLUMN     "caja" TEXT,
ADD COLUMN     "cambio" DECIMAL(18,4),
ADD COLUMN     "cant_dias" INTEGER,
ADD COLUMN     "clieasi" TEXT,
ADD COLUMN     "concepto" TEXT DEFAULT 'VENTAS',
ADD COLUMN     "cta_caja" TEXT,
ADD COLUMN     "cta_iva" TEXT,
ADD COLUMN     "cta_iva05" TEXT,
ADD COLUMN     "cuenta_exe" TEXT,
ADD COLUMN     "exen_dolar" DECIMAL(18,2),
ADD COLUMN     "form_pag" TEXT,
ADD COLUMN     "forma_devo" TEXT,
ADD COLUMN     "generar" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "irpc" DECIMAL(18,2),
ADD COLUMN     "ivasimplificado" DECIMAL(18,2),
ADD COLUMN     "moneda" TEXT,
ADD COLUMN     "nroFacAso" TEXT,
ADD COLUMN     "origen" TEXT,
ADD COLUMN     "reproceso" BOOLEAN DEFAULT false,
ADD COLUMN     "rucvennrotim" TEXT,
ADD COLUMN     "tkdesde" TEXT,
ADD COLUMN     "tkhasta" TEXT,
ADD COLUMN     "usu_ide" TEXT,
ADD COLUMN     "valor" DECIMAL(18,2),
ADD COLUMN     "ven_aux" TEXT,
ADD COLUMN     "ven_centro" TEXT,
ADD COLUMN     "ven_clie" TEXT,
ADD COLUMN     "ven_clinom" TEXT,
ADD COLUMN     "ven_con" TEXT,
ADD COLUMN     "ven_ctrl" TEXT,
ADD COLUMN     "ven_cuense" TEXT,
ADD COLUMN     "ven_cuenta" TEXT,
ADD COLUMN     "ven_cuota" TEXT,
ADD COLUMN     "ven_disexe" DECIMAL(18,2),
ADD COLUMN     "ven_disg05" DECIMAL(18,2),
ADD COLUMN     "ven_disgra" DECIMAL(18,2),
ADD COLUMN     "ven_exenta" DECIMAL(18,2),
ADD COLUMN     "ven_fecha" TEXT,
ADD COLUMN     "ven_fecven" TEXT,
ADD COLUMN     "ven_gra05" DECIMAL(18,2),
ADD COLUMN     "ven_gravad" DECIMAL(18,2),
ADD COLUMN     "ven_imputa" TEXT,
ADD COLUMN     "ven_iva" DECIMAL(18,2),
ADD COLUMN     "ven_iva05" DECIMAL(18,2),
ADD COLUMN     "ven_numero" TEXT,
ADD COLUMN     "ven_retenc" DECIMAL(18,2),
ADD COLUMN     "ven_rubg05" DECIMAL(18,2),
ADD COLUMN     "ven_rubgra" DECIMAL(18,2),
ADD COLUMN     "ven_sucurs" TEXT DEFAULT '1',
ADD COLUMN     "ven_tipimp" TEXT NOT NULL DEFAULT 'I',
ADD COLUMN     "ven_tipofa" TEXT,
ADD COLUMN     "ven_totfac" DECIMAL(18,2),
ADD COLUMN     "ventirpexe" DECIMAL(18,2),
ADD COLUMN     "ventirpgra" DECIMAL(18,2),
ADD COLUMN     "ventirptip" TEXT;
